include ../../mk/distro-include.mk

################################################################
# Example of implementation specific distro command
# Uncomment by removing first # it to try
################################################################

## help: my custom rule (this line will be show by 'make help')
#custom-rule-example:
#	@echo some custom distro command can be implement hier
#.PHONY: custom-rule-example

################################################################
