version: '3'
services:
  doccano:
    networks:
      - traefik
    image: "coronawhy/doccano"
    container_name: "doccano"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.doccano.entrypoints=web"
      - "traefik.http.routers.doccano.rule=Host(`doccano.${traefikhost}`)"

