version: '3'
services:  
  indra:
    image: labsyspharm/indra
    command: python /sw/indra/rest_api/api.py
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.indra.rule=Host(`indra.${traefikhost}`)"
      - "traefik.http.services.indra.loadbalancer.server.port=8080"
