version: '3.7'
services:
    namespaces:
      image: coronawhy/semantic-gateway
      ports:
        - "8002:80"
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.namespaces.rule=Host(`ns.${traefikhost}`)"
        - "traefik.http.routers.namespaces.tls=true"
        - "traefik.http.routers.namespaces.tls.certresolver=myresolver"
