version: '3.7'
services:
    nde:
      image: coronawhy/nde
      ports:
        - "8003:8080"
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.nde.rule=Host(`nde.${traefikhost}`)"
        - "traefik.http.services.nde.loadbalancer.server.port=8080"
        - "traefik.http.routers.nde.tls=true"
        - "traefik.http.routers.nde.tls.certresolver=myresolver"
