version: '3.7'
services:
    fuseki:
      container_name: skosmos-fuseki
      image: coronawhy/fuseki:latest
      #build: jena-fuseki/
      #image: stain/jena-fuseki
      environment:
        - ADMIN_PASSWORD=admin
        - JVM_ARGS=-Xmx6g 
          #--config=/data/skosmos.ttl
        - FUSEKI_DATASET_1=skosmos
        - FUSEKI_ADDITIONAL_ARGS=/data/jena-text.jar
      ports:
       - 3030:3030
      volumes:
        - ./var/skosmos/config/config.ttl:/fuseki/config.ttl
        - ./var/skosmos/config/fuseki-server:/jena-fuseki/fuseki-server
        - ./var/skosmos/data/fuseki-data:/fuseki/databases
        - ./var/skosmos/data/fuseki-input:/data
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.fuseki.rule=Host(`fuseki.${traefikhost}`)"
        - "traefik.http.services.fuseki.loadbalancer.server.port=3030"
        - "traefik.http.routers.fuseki.tls=true"
        - "traefik.http.routers.fuseki.tls.certresolver=myresolver"

    skosmos:
      networks:
        - traefik
      container_name: skosmos
      build: .
      volumes:
        - ./skosmos/Skosmos:/var/www/html
      ports:
        - 8000:80
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.skosmos.rule=Host(`skosmos.${traefikhost}`)"
        - "traefik.http.services.skosmos.loadbalancer.server.port=80"
        - "traefik.http.routers.skosmos.tls=true"
        - "traefik.http.routers.skosmos.tls.certresolver=myresolver"
      depends_on:
        - fuseki

