version: '3.7'
services:
    dataverse:
      #image: coronawhy/dataverse:5.4-cv
      image: coronawhy/dataverse:5.3
      # privileged: true
      ports:
        #- "443:443"
        - "4848:4848"
        - "8085:8080"
      env_file:
        - .env
      environment:
        - "CVM_SERVER_NAME=CESSDA" #Optional
        - "CVM_SERVER_URL=https://ns.${traefikhost}" # TODO: migrate to .env.example
        - "CVM_TSV_SOURCE=https://raw.githubusercontent.com/Dans-labs/semantic-gateway/main/conf/CMM_Custom_MetadataBlock.tsv"
        #- "WAR_FILE=https://github.com/IQSS/dataverse-docker/releases/download/5.2-cv/dataverse-5.2-cv.war"
        #- "WAR_FILE=https://github.com/IQSS/dataverse/releases/download/v5.3/dataverse-5.3.war"

        - "DOCKER_BUILD=true"
        - "CVM_SQL=https://github.com/IQSS/dataverse-docker/releases/download/5.2-cv/cv-update.sql"
        - "CVM_CONFIG=https://github.com/IQSS/dataverse-docker/releases/download/5.2-cv/cv-keywords.json"
        - "LANG=en"
        - "cvManager=http://"
        - "BUNDLEPROPERTIES=Bundle.properties"
        - "ADMIN_EMAIL=root@localhost"
        - "MAIL_SERVER=mailrelay"
        
        ########################################
        # Next section MUST BE overwritten by --env-file when docker-compose is launched
        ########################################
        
        - "JVM_OPTS='-Xmx10g -Xms10g -XX:MaxPermSize=20g -XX:PermSize=20g'"
      depends_on:
        - solr
#        - ns
      volumes:
        - ./var/dataverse/data:/usr/local/payara5/glassfish/domains/domain1/autodeploy
        - ./var/dataverse/dumps:/dumps
        - ./var/dataverse/docroot:/docroot
        - ./var/dataverse/metadata:/metadata
        - ./secrets:/secrets
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.dataverse.rule=Host(`www.${traefikhost}`)"
        - "traefik.http.services.dataverse.loadbalancer.server.port=8080"
        - "traefik.http.routers.dataverse.tls=true"
        - "traefik.http.routers.dataverse.tls.certresolver=myresolver"  

