version: '3.7'
services:
    dataverse:
            #image: coronawhy/dataverse:5.4-cv
      image: dataverse:5.3
      user: root
      # privileged: true

      environment:
        # ${var} is defined in .env file that is located in current folder
        - "DATAVERSE_URL=https://${traefikhost}"
        - "dataverse_fqdn=dataverse.$traefikhost"
        - "DATAVERSE_DB_HOST=$db_host"
        - "DATAVERSE_DB_USER=$db_user"
        - "DATAVERSE_DB_PASSWORD=$db_password"
        - "DATAVERSE_DB_NAME"
        - "DATAVERSE_SERVICE_HOST"
          #        - "DATAVERSE_URL"
        - "SOLR_SERVICE_HOST"
        - "SOLR_SERVICE_PORT"
        - "POSTGRES_SERVER=$db_host"
        - "POSTGRES_PORT=$db_port"
        - "POSTGRES_DATABASE=$db_name"
        - "POSTGRES_USER=$db_user"
        - "POSTGRES_PASSWORD=$db_password"
        - "baseuri=${traefikhost}"
        - "JVM_OPTS='-Xmx10g -Xms10g -XX:MaxPermSize=20g -XX:PermSize=20g'"
      depends_on:
        - solr
        - postgres
      volumes:
              #- ./var/dataverse/data:/usr/local/payara5/glassfish/domains/domain1/autodeploy
        - /media/dataverse-data:/data
        - ./var/dataverse/dumps:/dumps
        - /media/dataverse-docroot:/docroot
        - ./var/dataverse/metadata:/metadata
        - ./secrets:/secrets
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.dataverse.rule=Host(`${traefikhost}`)"
        - "traefik.http.services.dataverse.loadbalancer.server.port=8080"
        - "traefik.http.routers.dataverse.tls=true"
        - "traefik.http.routers.dataverse.tls.certresolver=myresolver"  

