version: '3.7'
services:
    postgres:
      ports:
        - "5433:5432"
      image: library/postgres:10.13
      restart: unless-stopped
      env_file:
        - .env
      volumes:
        - ./var/database/data:/var/lib/postgresql/data/ # persist data even if container shuts down
