version: '3.7'
services:
    solr:
            #image: ekoindarto/solr-cvm:latest
      image: iqss/solr-k8s
      #privileged: true
      environment:
        - "SOLR_JAVA_MEM=-Xms2g -Xmx2g"
      volumes:
              #- /media/dataverse-solr/data:/var/solr/data
        - ./var/solr/data:/var/solr/data
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.solr.rule=Host(`solr.${traefikhost}`)"
        - "traefik.http.services.solr.loadbalancer.server.port=8983"
        - "traefik.http.routers.solr.tls=true"
        - "traefik.http.routers.solr.tls.certresolver=myresolver"  

