version: '3.7'
services:
    solr:
      #image: ekoindarto/solr-cvm:latest
      image: coronawhy/solr:latest
      #image: iqss/solr-k8s:latest
      # entrypoint: "/bin/sh -c 'while :; do env; echo ========; sleep 20;done'"
      privileged: true
      ports:
        - "8983:8983"
      environment:
        - "SOLR_HOST=solr"
        - "SOLR_PORT=8983"
        - "SOLR_JAVA_MEM=-Xms1g -Xmx1g"
        - "SOLR_LOG_LEVEL=info"
      volumes:
        #- /media/dataverse-solr/data:/var/solr/data
        # opt/solr/server/solr/collection1/data
        - ./var/solr:/var/solr
      # user: "${UID}:${GID}"
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.solr.rule=Host(`solr.${traefikhost}`)"
        - "traefik.http.services.solr.loadbalancer.server.port=8983"
        - "traefik.http.routers.solr.tls=true"
        - "traefik.http.routers.solr.tls.certresolver=myresolver"  

